---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: armand-tensorpack-mask-rcnn-p3
  region: us-east-1

nodeGroups:
  - name: ng-c5-1b
    instanceType: c5.4xlarge
    availabilityZones: ["us-east-1b"]
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        imageBuilder: true
        ebs: true
        fsx: true
        efs: true
    ssh:
      allow: true
      publicKeyName: 'us-east-1-benchmark-tf'

